---

language: node_js

node_js: lts/*

script:
  - npm run lint
  - npm run build

deploy:
  - provider: pages
    skip_cleanup: true
    github-token: $GH_TOKEN
    local-dir: docs
    keep-history: false
    fqdn: system76.party
    on:
      repo: system76/web-party
      branch: master
